name: Terraform CI/CD
on: push
env:
    AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
    AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

jobs:
  terraform:
    name: terraform   
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v2   

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

 
      - name: Terraform Plan
        run: terraform plan -input=false

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false
        
      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

